#! /usr/bin/env python
# -*- python -*-

from __future__ import print_function
import os
import sys
import argparse

def main():

    parser = argparse.ArgumentParser(description='')

    ## paths
    parser.add_argument('filepath1', nargs='?')
    parser.add_argument('filepath2', nargs='?')

    # ## general options
    # parser.add_argument('--del', dest='delete', action='store_true')
    # parser.add_argument('-t', '--type', action='store_true', help='')

    # ## tree options
    # parser.add_argument('--scan')
    # parser.add_argument('--sort')

    # parser.add_argument('-ge', '--getentries', action='store_true')
    # parser.add_argument('-s', '--selection', default='')
    # parser.add_argument('-ce', '--count', action='store_true')

    # ## histogram options
    # parser.add_argument('-gb', '--getbin')

    args = parser.parse_args()

    file_path_1, file_path_2 = args.filepath1, args.filepath2

    if file_path_1 is None or file_path_2 is None:
        parser.print_usage()
        return 1


    print('Implement diff between file1 and file2')


if __name__ == '__main__':
    main()
